### ISSUE TITLE
is there any way to get samples decision path in vfdt.py?

### ISSUE THREAD

**Issue by liuchangjie** [doubleplusplus/incremental_decision_tree-CART-Random_Forest_python#3]
For example, a thousand samples have been trained with the vfdt.py, how could I get each sample's decision path and which leaf it will fall into？

**Comment by doubleplusplus** [comment]
the `sort_example` method can return the deciding leaf

recursively tracing back from the leaf and find its parent, grand parent and so on, until it find the root. I didn't code this method, it should be easy.

**Comment by liuchangjie** [comment]
> the `sort_example` method can return the deciding leaf
> 
> recursively tracing back from the leaf and find its parent, grand parent and so on, until it find the root. I didn't code this method, it should be easy.

**Comment by liuchangjie** [comment]
thank you so much, I will try to code.
